spring:
  application:
    name: old-system
  datasource:
    url: jdbc:postgresql://localhost:5432/notedb
    username: postgres
    password: aboba
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 1000
        order_inserts: true
    open-in-view: false